#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 22 12:29:05 2022

@author: gardi
"""

import numpy as np
import matplotlib.pyplot as plt


n = 35
R = 25e-3 # unit: m
I = 10 # unit: A
mu_0 = 4*np.pi*1e-7 # unit: T. m/A

d = 25e-3 #R # unit m
stepsize = 10e-6 # unit: m
x_start = 0  # unit: m
x_end = d # unit: m

X = np.arange(x_start, x_end, stepsize)
numOfSteps = X.shape[0]

B1 = np.zeros((int(numOfSteps))) # magnetic field produced by coil 1 at a distance x from it's centre # unit: T
B2 = np.zeros((int(numOfSteps))) # magnetic field produced by coil 2 at a distance x from it's centre # unit: T
B2T = np.zeros((int(numOfSteps))) # magnetic field produced by coil 2 at a distance x from the centre of coil 1 # unit: T
B = np.zeros((int(numOfSteps))) # sum of the magnetic field produced by coil 1 and coil 2 at a distance x from coil 1's centre # unit: T

for index, x in enumerate(X):
    y = x_end - x
    B1[index] = mu_0 * n * (I) * R**2 / (2 * (R**2 + x**2)**(3/2))
    B2[numOfSteps - index - 1] = mu_0 * n * (I) * R**2 / (2 * (R**2 + y**2)**(3/2))
    B2T[index] = mu_0 * n * I * R**2 / (2 * (R**2 + y**2)**(3/2))
    
    B[index] = B1[index] + B2[numOfSteps - index - 1]
    
plt.figure()
plt.plot(np.arange(x_start, x_end, stepsize) * 1000, B*1000, c='r', label="total field")
plt.plot(np.arange(x_start, x_end, stepsize) * 1000, B1*1000, c='b', label="field generated by coil 1")
plt.plot(np.arange(x_start, x_end, stepsize) * 1000, B2T*1000, c='k', label="field generated by coil 2")
plt.legend()

plt.figure()
plt.plot(np.arange(x_start, x_end, stepsize) * 1000, np.gradient(B*1000), c='r', label="gradient of total field")
plt.plot(np.arange(x_start, x_end, stepsize) * 1000, np.gradient(B1*1000), c='b', label="gradient of field generated by coil 1")
plt.plot(np.arange(x_start, x_end, stepsize) * 1000, np.gradient(B2T*1000), c='k', label="gradient of field generated by coil 2")
plt.legend()

plt.show()


#%%